/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JTabbedPane;

/**
 * @author Fabio Saruwataru
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JTabbedPane();
        telaPrincipalJPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        telaCadastrarItemJPanel = new javax.swing.JPanel();
        tituloCadastrarLbl = new javax.swing.JLabel();
        nomeItemLbl = new javax.swing.JLabel();
        descricaoItemLbl = new javax.swing.JLabel();
        marcaItemLbl = new javax.swing.JLabel();
        modeloItemLbl = new javax.swing.JLabel();
        serialNumberItemLbl = new javax.swing.JLabel();
        quatidadeItemLbl = new javax.swing.JLabel();
        valorVarejoItemLbl = new javax.swing.JLabel();
        valorAtacadoItemLbl = new javax.swing.JLabel();
        categoriaItemLbl = new javax.swing.JLabel();
        corItemLbl = new javax.swing.JLabel();
        nomeItemTf = new javax.swing.JTextField();
        descricaoItemTf = new javax.swing.JTextField();
        marcaItemTf = new javax.swing.JTextField();
        modeloItemTf = new javax.swing.JTextField();
        serialNumberTf = new javax.swing.JTextField();
        quantidadeItemTf = new javax.swing.JTextField();
        valorVarejoItemTf = new javax.swing.JTextField();
        valorAtacadoItemTf = new javax.swing.JTextField();
        categoriaItemTf = new javax.swing.JTextField();
        corItemTf = new javax.swing.JTextField();
        cadastrarBtn = new javax.swing.JButton();
        telaConsultarItemJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        telaAtualizarItemJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        telaApagarItemJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        abaCadastrarBtn = new javax.swing.JButton();
        abaConsultarBtn = new javax.swing.JButton();
        abaApagarBtn = new javax.swing.JButton();
        abaAtualizarBtn = new javax.swing.JButton();
        abaPrincipalBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tela.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tela Principal");

        javax.swing.GroupLayout telaPrincipalJPanelLayout = new javax.swing.GroupLayout(telaPrincipalJPanel);
        telaPrincipalJPanel.setLayout(telaPrincipalJPanelLayout);
        telaPrincipalJPanelLayout.setHorizontalGroup(
            telaPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPrincipalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        telaPrincipalJPanelLayout.setVerticalGroup(
            telaPrincipalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPrincipalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        tela.addTab("telaPrincipal", telaPrincipalJPanel);

        telaCadastrarItemJPanel.setPreferredSize(new java.awt.Dimension(542, 500));
        telaCadastrarItemJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCadastrarLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloCadastrarLbl.setText("Cadastrar item");
        telaCadastrarItemJPanel.add(tituloCadastrarLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 36));

        nomeItemLbl.setText("Nome do item:");
        telaCadastrarItemJPanel.add(nomeItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 51, -1, -1));

        descricaoItemLbl.setText("Descrição:");
        telaCadastrarItemJPanel.add(descricaoItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 79, -1, -1));

        marcaItemLbl.setText("Marca:");
        telaCadastrarItemJPanel.add(marcaItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 107, -1, -1));

        modeloItemLbl.setText("Modelo:");
        telaCadastrarItemJPanel.add(modeloItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 135, -1, -1));

        serialNumberItemLbl.setText("Serial Number:");
        telaCadastrarItemJPanel.add(serialNumberItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 163, -1, -1));

        quatidadeItemLbl.setText("Quantidade:");
        telaCadastrarItemJPanel.add(quatidadeItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 191, -1, -1));

        valorVarejoItemLbl.setText("Valor varejo:");
        telaCadastrarItemJPanel.add(valorVarejoItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 219, -1, -1));

        valorAtacadoItemLbl.setText("Valor atacado:");
        telaCadastrarItemJPanel.add(valorAtacadoItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 247, -1, -1));

        categoriaItemLbl.setText("Categoria:");
        telaCadastrarItemJPanel.add(categoriaItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 275, -1, -1));

        corItemLbl.setText("Cor:");
        telaCadastrarItemJPanel.add(corItemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 303, -1, -1));
        telaCadastrarItemJPanel.add(nomeItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 48, 240, -1));
        telaCadastrarItemJPanel.add(descricaoItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 76, 240, -1));
        telaCadastrarItemJPanel.add(marcaItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 104, 240, -1));
        telaCadastrarItemJPanel.add(modeloItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 132, 240, -1));
        telaCadastrarItemJPanel.add(serialNumberTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 160, 240, -1));
        telaCadastrarItemJPanel.add(quantidadeItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 188, 240, -1));
        telaCadastrarItemJPanel.add(valorVarejoItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 216, 240, -1));
        telaCadastrarItemJPanel.add(valorAtacadoItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 244, 240, -1));
        telaCadastrarItemJPanel.add(categoriaItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 272, 240, -1));
        telaCadastrarItemJPanel.add(corItemTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 300, 240, -1));

        cadastrarBtn.setText("Cadastrar");
        telaCadastrarItemJPanel.add(cadastrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 340, 110, -1));

        tela.addTab("telaCadastrar", telaCadastrarItemJPanel);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Consultar item");

        javax.swing.GroupLayout telaConsultarItemJPanelLayout = new javax.swing.GroupLayout(telaConsultarItemJPanel);
        telaConsultarItemJPanel.setLayout(telaConsultarItemJPanelLayout);
        telaConsultarItemJPanelLayout.setHorizontalGroup(
            telaConsultarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaConsultarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        telaConsultarItemJPanelLayout.setVerticalGroup(
            telaConsultarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaConsultarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        tela.addTab("telaConsultar", telaConsultarItemJPanel);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Atualizar item");

        javax.swing.GroupLayout telaAtualizarItemJPanelLayout = new javax.swing.GroupLayout(telaAtualizarItemJPanel);
        telaAtualizarItemJPanel.setLayout(telaAtualizarItemJPanelLayout);
        telaAtualizarItemJPanelLayout.setHorizontalGroup(
            telaAtualizarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAtualizarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        telaAtualizarItemJPanelLayout.setVerticalGroup(
            telaAtualizarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAtualizarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        tela.addTab("telaAtualizar", telaAtualizarItemJPanel);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Apagar item");

        javax.swing.GroupLayout telaApagarItemJPanelLayout = new javax.swing.GroupLayout(telaApagarItemJPanel);
        telaApagarItemJPanel.setLayout(telaApagarItemJPanelLayout);
        telaApagarItemJPanelLayout.setHorizontalGroup(
            telaApagarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaApagarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        telaApagarItemJPanelLayout.setVerticalGroup(
            telaApagarItemJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaApagarItemJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        tela.addTab("telaApagar", telaApagarItemJPanel);

        getContentPane().add(tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -39, -1, 440));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        abaCadastrarBtn.setText("Cadastrar");
        abaCadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaCadastrarBtnActionPerformed(evt);
            }
        });

        abaConsultarBtn.setText("Consultar");
        abaConsultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaConsultarBtnActionPerformed(evt);
            }
        });

        abaApagarBtn.setText("Apagar");
        abaApagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaApagarBtnActionPerformed(evt);
            }
        });

        abaAtualizarBtn.setText("Atualizar");
        abaAtualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaAtualizarBtnActionPerformed(evt);
            }
        });

        abaPrincipalBtn.setText("Principal");
        abaPrincipalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaPrincipalBtnActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sua logo aqui");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abaPrincipalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abaApagarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abaCadastrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(abaAtualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abaConsultarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abaApagarBtn, abaAtualizarBtn, abaCadastrarBtn, abaConsultarBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(abaPrincipalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abaCadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abaConsultarBtn)
                .addGap(18, 18, 18)
                .addComponent(abaAtualizarBtn)
                .addGap(18, 18, 18)
                .addComponent(abaApagarBtn)
                .addGap(69, 69, 69))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {abaApagarBtn, abaAtualizarBtn, abaCadastrarBtn, abaConsultarBtn});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abaPrincipalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaPrincipalBtnActionPerformed

        tela.setSelectedIndex(0);

    }//GEN-LAST:event_abaPrincipalBtnActionPerformed

    private void abaCadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaCadastrarBtnActionPerformed
        
        tela.setSelectedIndex(1);
        
    }//GEN-LAST:event_abaCadastrarBtnActionPerformed

    private void abaConsultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaConsultarBtnActionPerformed
        
        tela.setSelectedIndex(2);
        
    }//GEN-LAST:event_abaConsultarBtnActionPerformed

    private void abaAtualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaAtualizarBtnActionPerformed
        
        tela.setSelectedIndex(3);
        
    }//GEN-LAST:event_abaAtualizarBtnActionPerformed

    private void abaApagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaApagarBtnActionPerformed
        
        tela.setSelectedIndex(4);
        
    }//GEN-LAST:event_abaApagarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abaApagarBtn;
    private javax.swing.JButton abaAtualizarBtn;
    private javax.swing.JButton abaCadastrarBtn;
    private javax.swing.JButton abaConsultarBtn;
    private javax.swing.JButton abaPrincipalBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel categoriaItemLbl;
    private javax.swing.JTextField categoriaItemTf;
    private javax.swing.JLabel corItemLbl;
    private javax.swing.JTextField corItemTf;
    private javax.swing.JLabel descricaoItemLbl;
    private javax.swing.JTextField descricaoItemTf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marcaItemLbl;
    private javax.swing.JTextField marcaItemTf;
    private javax.swing.JLabel modeloItemLbl;
    private javax.swing.JTextField modeloItemTf;
    private javax.swing.JLabel nomeItemLbl;
    private javax.swing.JTextField nomeItemTf;
    private javax.swing.JTextField quantidadeItemTf;
    private javax.swing.JLabel quatidadeItemLbl;
    private javax.swing.JLabel serialNumberItemLbl;
    private javax.swing.JTextField serialNumberTf;
    private javax.swing.JTabbedPane tela;
    private javax.swing.JPanel telaApagarItemJPanel;
    private javax.swing.JPanel telaAtualizarItemJPanel;
    private javax.swing.JPanel telaCadastrarItemJPanel;
    private javax.swing.JPanel telaConsultarItemJPanel;
    private javax.swing.JPanel telaPrincipalJPanel;
    private javax.swing.JLabel tituloCadastrarLbl;
    private javax.swing.JLabel valorAtacadoItemLbl;
    private javax.swing.JTextField valorAtacadoItemTf;
    private javax.swing.JLabel valorVarejoItemLbl;
    private javax.swing.JTextField valorVarejoItemTf;
    // End of variables declaration//GEN-END:variables
}
